force-app/main/default/objects/Neighborhood_Introduction__c/Neighborhood_Introduction__c.object-meta.xml
<CustomObject>
    <label>Neighborhood Introduction</label>
    <nameField>
        <label>Neighborhood Introduction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Neighborhood Introductions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Neighborhood_Introduction_Article__c/Neighborhood_Introduction_Article__c.object-meta.xml
<CustomObject>
    <label>Neighborhood Introduction Article</label>
    <nameField>
        <label>Neighborhood Introduction Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Neighborhood Introduction Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Neighborhood_Introduction_Article__c/fields/neighborhood_introduction__c.field-meta.xml
<CustomField>
    <fullName>neighborhood_introduction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Neighborhood Introduction</label>
    <referenceTo>Neighborhood_Introduction__c</referenceTo>
    <relationshipLabel>Neighborhood Introduction Articles</relationshipLabel>
    <relationshipName>Neighborhood_Introduction_Articles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Neighborhood_Introduction_Article__c/fields/sub_introduction__c.field-meta.xml
<CustomField>
    <fullName>sub_introduction__c</fullName>
    <label>Sub Introduction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Neighborhood_Introduction_Article__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NeighborhoodIntroduction.cls
public with sharing class NeighborhoodIntroduction {
    @AuraEnabled(cacheable=true)
    public static List<Neighborhood_Introduction__c> getNeighborhoodIntroduction(){
        try {
            return [SELECT Id, title__c, sub_introduction__c FROM Neighborhood_Introduction__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Neighborhood_Introduction_Article__c> getNeighborhoodIntroductionArticle(Id neighborhoodIntroductionId){
        try {
            return [SELECT Id, image_path__c, title__c, content__c FROM Neighborhood_Introduction_Article__c WHERE neighborhood_introduction__c =: neighborhoodIntroductionId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
} 