force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/capacity__c.field-meta.xml
<CustomField>
    <fullName>capacity__c</fullName>
    <label>Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/introduction__c.field-meta.xml
<CustomField>
    <fullName>introduction__c</fullName>
    <label>Introduction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/size__c.field-meta.xml
<CustomField>
    <fullName>size__c</fullName>
    <label>Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/sub_title__c.field-meta.xml
<CustomField>
    <fullName>sub_title__c</fullName>
    <label>Sub title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting_image__c/Meeting_image__c.object-meta.xml
<CustomObject>
    <label>Meeting image</label>
    <nameField>
        <label>Meeting image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_image__c/fields/image_path__c.field-meta.xml
<CustomField>
    <fullName>image_path__c</fullName>
    <label>Image path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting_image__c/fields/meeting__c.field-meta.xml
<CustomField>
    <fullName>meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting images</relationshipLabel>
    <relationshipName>Meeting_images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Meeting.cls
public with sharing class Meeting {
    @AuraEnabled(cacheable=true)
    public static List<Meeting__c> getMeetings(){
        try {
            return [SELECT Id, title__c, sub_title__c, introduction__c,capacity__c, size__c,description__c FROM Meeting__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Meeting_image__c> getMeetingImages(Id meetingId){
        try {
            return [SELECT Id, image_path__c FROM Meeting_image__c WHERE meeting__c =: meetingId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}