force-app/main/default/objects/hero_page__c/hero_page__c.object-meta.xml
<CustomObject>
    <label>Hero Page</label>
    <nameField>
        <label>Hero Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hero Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/hero_page__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/hero_page__c/fields/image_path__c.field-meta.xml
<CustomField>
    <fullName>image_path__c</fullName>
    <label>Image</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hero_page__c/fields/page_route__c.field-meta.xml
<CustomField>
    <fullName>page_route__c</fullName>
    <label>Page Route</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hero_page__c/fields/sub_title__c.field-meta.xml
<CustomField>
    <fullName>sub_title__c</fullName>
    <label>Sub Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HeroPage.cls
public with sharing class HeroPage {
    @AuraEnabled(cacheable=true)
    public static List<hero_page__c> getHeroOfPage(String pageRoute) {
        try {
            return [SELECT Id, title__c, sub_title__c, description__c, image_path__c  FROM hero_page__c WHERE page_route__c =: pageRoute];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}